### ISSUE TITLE
Integration Tests for Installers on a Periodic Basis

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-self-hosted-installers#104]
Currently, no tests exist for the self-hosted installers with the exception of the basic installer. We should create some tests which can validate the fact that installers are in working order without manual intervention.

Potential tests:
- ensure the console URL is reachable and returning a 200
- ensure the api URL is reachable and returning a 200  (/api/status)

Org and user are not created with self-hosted service (requires manual step). Would be ideal to have an auto created org/user to allow stack operations, policy pack operations, etc to be executed against the service to exercise more functionality.

**Comment by rshade** [comment]
Closing this in favor of #44
