### ISSUE TITLE
Add ingress allow list to GKE hosted installer

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-self-hosted-installers#105]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Add ingress "allow list" to GKE hosted installer

**Comment by MitchellGerdisch** [comment]
Solved byhttps://github.com/pulumi/pulumi-self-hosted-installers/pull/136
