### ISSUE TITLE
Add integration test with Azure services

### ISSUE THREAD

**Issue by praneetloke** [pulumi/pulumi-self-hosted-installers#18]
With #16 the ability to run the service with different configurations was demonstrated as well as an integration test that tests Minio as the object storage was added. We should also add one for Azure services (Storage and Azure KeyVault). The test `TestStackUpdateForMinioStorage`, although meant for Minio, isn't entirely specific to Minio except for the head of the test function that checks if the endpoint scheme is s3. In other words, we should split that function so that the rest of the function is generic to simply initializing a Pulumi app and running a stack update which is not specific to any kind of object storage.

With this issue, what we will need is the infrastructure in Azure for object storage and KeyVault for encryption. I'd like to suggest that we create the necessary infrastructure during the test and tear them down before the test wraps up as well. In addition to the Azure infrastructure, we'll also need to add a test that exercises the encryption path for a stack's key material, i.e. adding a secret stack config (`pulumi config set --secret someSecretName`)

**Comment by rshade** [comment]
closing this in favor of #44
