### ISSUE TITLE
Typo in containerDef for migrationsService

### ISSUE THREAD

**Issue by sfc-gh-jlove** [pulumi/pulumi-self-hosted-installers#60]
https://github.com/pulumi/pulumi-self-hosted-installers/blob/e6c65d0ef2939dfb1f2069177f81ff21e1450406/ecs-hosted/go/application/service/migrationsService.go#L110

**Comment by sfc-gh-jlove** [comment]
" migrations-task" should be "migrations-task"

**Comment by phillipedwards** [comment]
fixed by  #61
