### ISSUE TITLE
DB Migration script doesn't pick up the `PULUMI_DATABASE_NAME` env variable

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-self-hosted-installers#88]
### What happened?

A customer using our self-hosted service reported that the database name is hardcoded in our `migrations` container. It is:

https://github.com/pulumi/pulumi-self-hosted-installers/blob/c709620dc7b0a684e85f9986e37562051f06992b/quickstart-docker-compose/scripts/migrate-db.sh#L79

### Steps to reproduce

Deploy a self-hosted setup:
* Create a database *not* named `pulumi`
* configure `PULUMI_DATABASE_NAME` for the `api` service to connect to the proper database.
* configure `PULUMI_DATABASE_NAME` for the `migrations` service.

### Expected Behavior

The value of the `PULUMI_DATABASE_NAME` environment variable should be picked up in line with the `api` service.

### Actual Behavior

You see this service still tries to connect to the `pulumi` database because it is hardcoded in the migrations script.

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by susanev** [comment]
@ringods do you need a triage on this issue? if not, do you mind dropping the needs-triage label?
